### ISSUE TITLE
Cumulative global map does not appear

### ISSUE THREAD

**Issue by xbillas** [Ikhyeon-Cho/height_mapping#4]
开启全局地图的节点之后，输出并没有出现累积的全局地图，请问时哪里有问题呢？
[HeightMapping::SensorProcessor]: Sensor processor initialized. Waiting for 3 rgb clouds... 
[HeightMapping::HeightMapping]: Height estimator type --> StatisticalMeanEstimator 
[HeightMapping::HeightMapping]: Height mapping node initialized. Waiting for scan inputs... 
[HeightMapping::HeightMapping]: Laser cloud Received! Use LiDAR sensor for height mapping... 
[HeightMapping::GlobalMapping]: Laser cloud received! Start global mapping...

**Comment by xbillas** [comment]
After opening the global map node, the cumulative global map does not appear in the output. Like the gif file you have shown. What is the problem?

**Comment by xbillas** [comment]
![Uploading height_mapping.gif…]()

**Comment by Ikhyeon-Cho** [comment]
@xbillas Hi, I've just tested and it works fine. 
Could you tell me how you launched the nodes?

Or, you can just try the following commands:
`roslaunch height_mapping run.launch global_mapping:=true`

- Please check `/height_mapping/globalmap/pointcloud` is published periodically as expected.
- Also, you should check that all the relevant packages like `grid_map` are compiled with `release` option.

If you have further questions, please let me know.

**Comment by xbillas** [comment]
thanks for your response @Ikhyeon-Cho ,i am sure that global_mapping is set true. And the topic is published periodically, the packages are also compiled with release option. but the data bag is my own.

**Comment by xbillas** [comment]
![height_mapping](https://github.com/user-attachments/assets/b8ce4e9a-74aa-4d00-b1b2-f4d82a9185be)

**Comment by Ikhyeon-Cho** [comment]
@xbillas 
From your data, it seems like your `/tf`, the transformation from `map` to `base_link`, is not properly set or estimated.
Did you manually publish the static transformation? Since the robot moves in the environment, the transformation should be dynamic, which implies that we should properly estimate the 3d robot poses.

If this is the case, then the local height map `/height_mapping/map/gridmap` will have the similar problem.

**Comment by xbillas** [comment]
It's indeed the problem you mentioned. thanks for your time. : )

**Comment by Ikhyeon-Cho** [comment]
No problem. Hope your work goes fine!
